// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.EmployerFinance.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("HMRC-Scenario-07-No-Payment-for-Period-and-Ceased-PAYE-Scheme")]
    public partial class HMRC_Scenario_07_No_Payment_For_Period_And_Ceased_PAYE_SchemeFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "Scenario-07-No-Payment-for-Period-and-Ceased-PAYE-Scheme.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "HMRC-Scenario-07-No-Payment-for-Period-and-Ceased-PAYE-Scheme", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Balance-should-remain-if-no-payment-occurs")]
        public void Balance_Should_Remain_If_No_Payment_Occurs()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Balance-should-remain-if-no-payment-occurs", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
 testRunner.Given("We have an account with a paye scheme", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "LevyDueYtd",
                            "Payroll_Year",
                            "Payroll_Month",
                            "English_Fraction",
                            "SubmissionDate",
                            "CreatedDate",
                            "LevyAllowanceForFullYear",
                            "NoPaymentForPeriod",
                            "DateCeased"});
                table29.AddRow(new string[] {
                            "999000701",
                            "1000",
                            "17-18",
                            "1",
                            "1",
                            "2017-04-15",
                            "2017-04-23",
                            "15000",
                            "",
                            ""});
                table29.AddRow(new string[] {
                            "999000702",
                            "2000",
                            "17-18",
                            "2",
                            "1",
                            "2017-05-15",
                            "2017-05-23",
                            "15000",
                            "true",
                            ""});
#line 5
 testRunner.And("Hmrc return the following submissions for paye scheme", ((string)(null)), table29, "And ");
#line hidden
#line 9
 testRunner.When("we refresh levy data for paye scheme on the 06/2017", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
 testRunner.And("all the transaction lines in this scenario have had their transaction date update" +
                        "d to the specified created date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
 testRunner.Then("we should see a level 1 screen with a balance of 1100 on the 06/2017", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Balance-should-not-be-affected-by-past-non-payment-months")]
        public void Balance_Should_Not_Be_Affected_By_Past_Non_Payment_Months()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Balance-should-not-be-affected-by-past-non-payment-months", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 15
 testRunner.Given("We have an account with a paye scheme", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "LevyDueYtd",
                            "Payroll_Year",
                            "Payroll_Month",
                            "English_Fraction",
                            "SubmissionDate",
                            "CreatedDate",
                            "LevyAllowanceForFullYear",
                            "NoPaymentForPeriod",
                            "DateCeased"});
                table30.AddRow(new string[] {
                            "999000703",
                            "1000",
                            "17-18",
                            "1",
                            "1",
                            "2017-04-15",
                            "2017-04-23",
                            "15000",
                            "",
                            ""});
                table30.AddRow(new string[] {
                            "999000704",
                            "0",
                            "17-18",
                            "2",
                            "1",
                            "2017-05-15",
                            "2017-05-23",
                            "15000",
                            "true",
                            ""});
                table30.AddRow(new string[] {
                            "999000705",
                            "2000",
                            "17-18",
                            "3",
                            "1",
                            "2017-06-15",
                            "2017-06-23",
                            "15000",
                            "",
                            ""});
#line 16
 testRunner.And("Hmrc return the following submissions for paye scheme", ((string)(null)), table30, "And ");
#line hidden
#line 21
 testRunner.When("we refresh levy data for paye scheme on the 07/2017", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
 testRunner.And("all the transaction lines in this scenario have had their transaction date update" +
                        "d to the specified created date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
 testRunner.Then("we should see a level 1 screen with a balance of 2200 on the 06/2017", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
