openapi: 3.0.0
info:
  version: '1.0'
  title: Finance job API's
  description: 'This API wraps the current direct to database calls that each job performs'
paths:
  /info:
    get:
      description: information regarding this API. The version will be returned
      responses:
        '200':
          $ref: '#/components/responses/infoResponse'  
  /health:
    get:
      description: The system is fully ready to accept requests and all the dependencies are healthy
      responses:
        '200':
          description: All health checks have passed
          $ref: '#/components/responses/healthCheckResponse'
        '503':
          description: A health check has failed
          $ref: '#/components/responses/healthCheckResponse'

  /jobs/import-payments/levy-import-payments/period-ends:
    post:
      summary: Endpoint for creating a new levy period end
      requestBody:
        $ref: '#/components/requestBodies/createLevyPeriodEndRequest'
      responses:
        '201':
          $ref: '#/components/responses/createdResponse'  
        '404':
          $ref: '#/components/responses/notFoundResponse'
    get:
      summary: Returns the period ends for levy
      parameters:
        - in: query
          name: orderBy
          schema:
            type: string
            enum: 
            - latest
            - earliest
          required: false
          description: The order by which to sort the results, default latest
      responses:
        '200':
          $ref: '#/components/responses/levyPeriodEndsResponse'  
        '404':
          $ref: '#/components/responses/notFoundResponse'
  
  /jobs/import-payments/levy-import-payments/period-ends/{id}:
    get:
      summary: Returns the period end for the id sent across form the consumer when created
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The id of the period end
      responses:
        '200':
          $ref: '#/components/responses/levyPeriodEndResponse'  
        '404':
          $ref: '#/components/responses/notFoundResponse'

  /jobs/import-payments/employer-accounts:
    get:
      description: Fetched a paged list of employer accounts
      responses:
        '200':
          $ref: '#/components/responses/pagedEmployerAccountsResponse'  
          
  /jobs/import-payments/employer-accounts/{id}:
    get:
      description: Fetched a specific accounnt
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: The id of the account
      responses:
        '200':
          $ref: '#/components/responses/pagedEmployerAccountsResponse'  
        '404':
          $ref: '#/components/responses/notFoundResponse'  
          
  
components:  
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
      description: "Enter your API key in the `Ocp-Apim-Subscription-Key` header."
  
  requestBodies:
    createLevyPeriodEndRequest:
      description: A request to create a period end for levy
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/levyPeriodEndRequest'
  
  headers:
    Location:
      description: The URL of the newly created resource
      schema:
        type: string
        format: uri
  
  responses:
    notFoundResponse:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            type: string
    
    createdResponse:
      description: common createdResponse
      headers:
        Location:
          $ref: '#/components/headers/Location'

    levyPeriodEndsResponse:
      description: A response for levy period ends
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/levyPeriodEnd'
        
    levyPeriodEndResponse:
      description: A response for levy period end
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/levyPeriodEnd'

    healthCheckResponse:
      description: Results of a health check
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/healthcheckResults'

    infoResponse:
      description: Information response
      content:
        text/plain:
          schema:
            type: string
            example: Leaner data APIM for the apprenticeship service - Version 3.0.2

    pagedEmployerAccountsResponse:
      description: A paged employer response
      headers:
        Link:
          description: Pagination links (next, prev)
          schema:
            type: string
            format: url
          example: '<https://api.example.com/items?page=2>; rel="prev", <https://api.example.com/items?page=5>; rel="next"'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/pagedEmployerAccounts'

  schemas:

    pagedEmployerAccounts:
      type: object
      properties:
        training:
          type: array
          items:
              $ref: '#/components/schemas/employerAccount'
        total:
          type: integer
          minimum: 0
        page: 
          type: integer
          minimum: 1
        pageSize: 
          type: integer
          minimum: 1
          maximum: 100
        totalPages: 
          type: integer
          minimum: 1
      required:
        - page
        - total
        - pageSize  
        - totalPages  
        
    employerAccount:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        hashedId:
          type: string
        publicHashedId:
          type: string
        legalEntities:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              pendingAggredmentId: 
                type: integer
              signedAgreementId:
                type: integer
              signedAgreementVersion:
                type: integer
                
    levyPeriodEndRequest:
      type: object
      properties:
        periodEndId: 
          type: string
        month: 
          type: integer
        year:
          type: integer
        accountValidDate:
          type: string
          format: date-time
        commitmentValidDate:
          type: string
          format: date-time
        completionDate:
          type: string
          format: date-time
        paymentsForPeriod:
          type: string

    levyPeriodEnd:
      allOf:
        - $ref: "#/components/schemas/levyPeriodEndRequest"
        - type: object
          properties:
            id:
              type: integer

    healthcheckResults:
      type: array
      items:
        $ref: '#/components/schemas/healthcheck' 
  
    healthcheck:
      type: object
      properties:
        description: 
          type: string
        result: 
          type: string 

security:
  - ApiKeyAuth: []  # Apply API Key security globally